version: "3.4"
services:
  simplesaml:
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: urn:memebase:fake-okta
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://memebase.docker:4000/sso/sp/consume/okta
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://memebase.docker:4000/sso/sp/logout/okta
      VIRTUAL_HOST: simplysaml.docker
    ports:
      - "8080:8080"
      - "8443:8443"

  s3:
    image: minio/minio
    volumes:
      - "./priv/uploads:/data"
    environment:
      MINIO_ACCESS_KEY: "ACCESSKEY"
      MINIO_SECRET_KEY: "SECRETKEY"
      VIRTUAL_HOST: s3.docker
    ports:
      - "9000:9000"
    command: "server /data"

  postgres:
    image: "postgres:11"
    container_name: memebase_postgres
    ports:
      - "54320:5432"

  memebase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "4000:4000"
        - "4001:4001"
    environment:
      DB_HOSTNAME: postgres
      HOST: 'http://memebase.docker:4000'
      BASE_URL: 'http://memebase.docker:4000/sso'
      VIRTUAL_HOST: memebase.docker
    depends_on:
      - s3
      - simplesaml
      - postgres
